[package]
authors = ["apx"]
name = "katharsis"
version = "0.1.0"

[dependencies]
hyper = "0.10.10"
hyper-native-tls = "0.2.2"
iso_country = "0.1.2"
json = "0.11.6"
rocket = "0.2.7"
rocket_codegen = "0.2.7"
serde_json = "1.0.2"
time = "0.1.37"
